name: Test Strict Windows
#Giả sử cần chạy trong khoảng 11h10 đến 11h29 và 12h30 đến 12h49
on:
  # Poll quanh khung (UTC = VN-7)
  schedule:
    - cron: "20-59/5 3 * * 1-5"  # 10:20..10:59 VN (03:25..03:55 UTC), T2–T6
    - cron: "00-19/5 4 * * 1-5"  # 10:59..11:29 VN (03:25..03:55 UTC), T2–T6
    - cron: "30-59/5 4 * * 1-5"   # 04:30 - 04:55 UTC = 11:30–11:55 VN
    - cron: "0-39/5 5 * * 1-5"    # 05:00, 05:05, ..., 05:45 UTC = 12:00–12:45 VN
  workflow_dispatch:
  
jobs:
  run_if_in_window:
    runs-on: ubuntu-latest  
    steps:
      - name: Print time (UTC & VN)
        run: |
          echo "UTC: $(date -u)"
          echo "VN : $(TZ='Asia/Ho_Chi_Minh' date)"

      # Xác định slot theo giờ VN; nếu ngoài slot thì skip
      - name: Detect VN slot & build window key
        id: slot
        run: |
          NOW="$(TZ='Asia/Ho_Chi_Minh' date +%H:%M)"
          TODAY="$(TZ='Asia/Ho_Chi_Minh' date +%Y%m%d)"
          echo "VN now: $NOW"

          SLOT="none"
          case "$NOW" in
            11:1[0-9]|11:2[0-9]) SLOT="slot1" ;;  # 11:10–11:29
            12:3[0-9]|12:4[0-9]) SLOT="slot2" ;;  # 12:30–12:49
          esac

          if [ "$SLOT" = "none" ]; then
            echo "Outside strict windows -> skip"
            echo "ok=false" >> $GITHUB_OUTPUT
            exit 78
          fi

          WINDOW_KEY="${SLOT}-${TODAY}"
          echo "WINDOW_KEY=$WINDOW_KEY" >> $GITHUB_ENV
          echo "ok=true" >> $GITHUB_OUTPUT
          echo "This run window key: $WINDOW_KEY"

      # Lock theo (slot + ngày): run đầu tiên tạo key; run sau cùng slot/ngày sẽ cache-hit -> skip
      - name: Window lock (first run wins)
        if: steps.slot.outputs.ok == 'true'
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/window-lock
          key: run-window-${{ env.WINDOW_KEY }}

      - name: Skip if already executed in this window today
        if: steps.slot.outputs.ok == 'true' && steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "🔒 Already executed for ${{ env.WINDOW_KEY }} -> skip"
          exit 78

      # ------ THỰC THI THẬT SỰ (chỉ 1 lần/khung/ngày) ------
      - name: Do the real thing
        if: steps.slot.outputs.ok == 'true' && steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "🚀 Executing ONCE for ${{ env.WINDOW_KEY }}"

